/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.awt.CardLayout;
import java.time.LocalDate;
import model.Car;
import model.CarFleet;

/**
 *
 * @author piyus
 */
        
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    CarFleet carFleetDetails;
    
    public MainJFrame() {
        initComponents();
        
        carFleetDetails = new CarFleet();
        uploadCarData();
    }

    public void uploadCarData(){
        
        //setting the default instances of car
        Car car1 = carFleetDetails.addNewCar();
        car1.setModelNumber(11111);
        car1.setSerialNumber(1);
        car1.setManufacturer("Honda");
        car1.setManufacturedDate(LocalDate.parse("2014-12-18"));
        car1.setSeatCapacity(2);
        car1.setPlatformUsed("Uber");
        car1.setIsAvailable(true);
        car1.setLastUpdated(LocalDate.parse("2017-11-15"));
        car1.setCity("New York");
        car1.setMaintenanceCertExpDate(LocalDate.parse("2020-11-11"));     

        Car car2 = carFleetDetails.addNewCar();
        car2.setModelNumber(22222);
        car2.setSerialNumber(2);
        car2.setManufacturer("Tesla");
        car2.setManufacturedDate(LocalDate.parse("2015-04-05"));
        car2.setSeatCapacity(4);
        car2.setPlatformUsed("Uber");
        car2.setIsAvailable(false);
        car2.setLastUpdated(LocalDate.parse("2021-10-01"));
        car2.setCity("Boston");
        car2.setMaintenanceCertExpDate(LocalDate.parse("2023-11-11"));   

        Car car3 = carFleetDetails.addNewCar();
        car3.setModelNumber(33333);
        car3.setSerialNumber(3);
        car3.setManufacturer("Tesla");
        car3.setManufacturedDate(LocalDate.parse("2021-04-05"));
        car3.setSeatCapacity(5);
        car3.setPlatformUsed("Ola");
        car3.setIsAvailable(true);
        car3.setLastUpdated(LocalDate.parse("2021-10-01"));
        car3.setCity("Los Angeles");
        car3.setMaintenanceCertExpDate(LocalDate.parse("2025-12-11"));  
        
        Car car4 = carFleetDetails.addNewCar();
        car4.setModelNumber(44444);
        car4.setSerialNumber(4);
        car4.setManufacturer("Audi");
        car4.setManufacturedDate(LocalDate.parse("2019-08-04"));
        car4.setSeatCapacity(3);
        car4.setPlatformUsed("Lyft");
        car4.setIsAvailable(true);
        car4.setLastUpdated(LocalDate.parse("2021-10-01"));
        car4.setCity("California");
        car4.setMaintenanceCertExpDate(LocalDate.parse("2029-03-27")); 
        
        Car car5 = carFleetDetails.addNewCar();
        car5.setModelNumber(55555);
        car5.setSerialNumber(5);
        car5.setManufacturer("Suzuki");
        car5.setManufacturedDate(LocalDate.parse("2017-10-24"));
        car5.setSeatCapacity(4);
        car5.setPlatformUsed("Uber");
        car5.setIsAvailable(false);
        car5.setLastUpdated(LocalDate.parse("2021-10-10"));
        car5.setCity("California");
        car5.setMaintenanceCertExpDate(LocalDate.parse("2021-03-19")); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnCreate.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnCreate.setText("Create Car");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnView.setText("View or Update Car");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnView});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnCreate)
                .addGap(93, 93, 93)
                .addComponent(btnView)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car Rental Service Management");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(carFleetDetails);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(carFleetDetails);
        splitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
